# .github/workflows/update-submodules.yml
name: Update Submodules

on:
  push:
    paths:
      - '.gitmodules'
      - 'frontend-repo/**'
      - 'backend-repo/**'
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        submodules: recursive 

    - name: Set Up Git User
      run: |
        git config --global user.email "majdbitar2003@gmail.com" # Update with your email
        git config --global user.name "Majdb15" # Update with your name

    - name: Update Submodules
      run: |
        git submodule update --remote --merge # Update submodules
        git add . # Stage changes
        git commit -m "Automated update of submodules" || echo "No changes to commit" # Commit changes
        git push origin main # Push changes to the repository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Authenticate API requests
